apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferencePool
metadata:
  name: gaie-deepseek-v3
  namespace: llm-d-deepseek-v3
  labels:
    app: gaie-deepseek-v3
    component: inferencepool
spec:
  targetPortNumber: 8000
  modelServerType: vllm
  selector:
    matchLabels:
      llm-d.ai/inferenceServing: "true"
  extensionRef:
    name: gaie-deepseek-v3-epp
    portNumber: 9002
    failureMode: FailClose
