apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: llm-d-llama31-pd-disaggregation
  namespace: llm-d-llama31
  labels:
    app: llm-d-llama31
    component: httproute
spec:
  parentRefs:
  - name: infra-llama31-inference-gateway
    namespace: llm-d-llama31
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    filters:
    - type: ExtensionRef
      extensionRef:
        group: inference.networking.x-k8s.io
        kind: InferencePool
        name: gaie-llama31
    backendRefs:
    - name: ms-llama31-llm-d-modelservice-prefill
      port: 8000
    - name: ms-llama31-llm-d-modelservice-decode
      port: 8200
