apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferencePool
metadata:
  name: gaie-llama31
  namespace: llm-d-llama31
  labels:
    app: gaie-llama31
    component: inferencepool
spec:
  targetPortNumber: 8000
  modelServerType: vllm
  selector:
    matchLabels:
      llm-d.ai/inferenceServing: "true"
  extensionRef:
    name: gaie-llama31-epp
    portNumber: 9002
    failureMode: FailClose
