apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: llm-d-llama31-pd-disaggregation
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: infra-llama31-inference-gateway
  rules:
    - backendRefs:
      - group: inference.networking.x-k8s.io
        kind: InferencePool
        name: gaie-llama31
        port: 8000
        weight: 1
      timeouts:
        backendRequest: 300s
        request: 300s
      matches:
      - path:
          type: PathPrefix
          value: /
